name: Build and Deploy React App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Node.js 설정
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    # 3. 종속성 설치
    - name: Install dependencies
      run: npm ci

    # 4. 빌드 React 애플리케이션
    - name: Build React app
      run: npm run build

    # 5. 배포를 위해 빌드 결과물 업로드
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write

    steps:
    # 1. 아티팩트 다운로드
    - name: Download artifact for deployment
      uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: ./build

    # 2. GitHub Pages에 배포
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
